# fly.toml app configuration file generated for ouroboros on 2026-02-13T16:07:13-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ouroboros'
primary_region = 'gru'

[build]

[env]
  DATA_DIR = '/data'
  PORT = '8080'
  STATIC_DIR = './frontend/dist'

[[mounts]]
  source = 'ouroboros_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[checks]
  [checks.health]
    port = 8080
    type = 'http'
    interval = '30s'
    timeout = '5s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
